DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    createdAt TIMESTAMP NOT NULL,
    CONSTRAINT url_key PRIMARY KEY (id)
);

DROP TABLE IF EXISTS url_checks;

CREATE TABLE url_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    urlId BIGINT NOT NULL,
    statusCode INTEGER NOT NULL,
    h1 VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    createdAt TIMESTAMP NOT NULL,
    CONSTRAINT url_checks_key PRIMARY KEY (id)
);

