run-dist:
	./build/install/app/bin/app
run:
	./gradlew run
test:
	./gradlew test
lint:
	./gradlew checkstyleMain
tint:
	./gradlew checkstyleTest
build:
	./gradlew build
	./gradlew checkstyleMain
	./gradlew checkstyleTest
report:	
	./gradlew jacocoTestReport
.PHONY: build
